name: Publish API Documentation
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          ref: 2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install -g bootprint bootprint-openapi gh-pages
      - run: make doc-version
      - run: >-
          CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot
          <pakkun@cliffano.com>" --repo "https://${{ secrets.STUDIO_GITHUB_TOKEN
          }}@github.com/cliffano/swaggy-jenkins.git"
