---
name: Release Major
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: git config --global user.email "pakkun@cliffano.com"
      - run: git config --global user.name "pakkunbot"
      - run: npm install -g rtk
      - run: rtk release --release-increment-type major
      - uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - run: npm install -g bootprint bootprint-openapi gh-pages
      - run: make doc-version
      - run: CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot <pakkun@cliffano.com>" --repo "https://${{ secrets.STUDIO_GITHUB_TOKEN }}@github.com/cliffano/swaggy-jenkins.git"